### ISSUE TITLE
Is the kernel produced for RVR correct?

### ISSUE THREAD

**Issue by thepav** [AmazaspShumik/Bayesian-Regression-Methods#14]
I have an X training vector passed in that is of shape (2,2219), but the RVR fit() function calls RegressionARD's fit() using a kernel K that is of shape (7,7). This results in my coefficients (coef_) being of size 7, which doesn't seem correct since my n_features is 2219.

is there an error in the get_kernel function?

**Comment by AmazaspShumik** [comment]
So you have data set with n_samples = 2, n_features  = 2219?

Algorithm assumes that input X is of size [n_samples,n_features], initial kernel matrix is of size [1,1]. Kernel matrix is iteratively increased to include all relevant vectors, note that maximum number of relevant vectors is equal to n_samples, in your case it can not be larger than 2. So n_features should not be 2219, however coef_ attribute obviously should not have shape (7,).

I have no idea how kernel size can become larger than n_samples, since I use 'pairwise_kernels' from sklearn for kernel construction !

I would suggest you to make small detailed ipython notebook illustrating problem, or share data so I can run experiment ( if it is not sensitive ). You can make pull request and contribute to user_examples folder.

Thanks for help.

**Comment by thepav** [comment]
Sorry that was a typo the shape is (7,2219). So 7 samples. 

If the kernel that comes out is supposed to be (7,7) then how does one example the coefficient weights assigned to each feature? Or am I completely missing the mark.

**Comment by AmazaspShumik** [comment]
1) Yes in your case maximum kernel size can be (7,7) as I explained in previous answer.

2) RVM does not assign coefficient to each feature , it uses features only for kernel construction and then   works in vector space spanned by vectors of kernel matrix, so you really can not determine coefficient for each feature.

3) If you want to find out coefficient for each feature you can use RegressionARD model.
