### ISSUE TITLE
shape of coef_ attribute 

### ISSUE THREAD

**Issue by olafwied** [AmazaspShumik/Bayesian-Regression-Methods#34]
I've been using the `RVC` model for binary classification and the shape of the `coef_` and the `active_` attribute after fitting is `(1,n_samples)` and not `(n_features)` what I had expected. What does the `coef_` attribute represent here?

**Comment by AmazaspShumik** [comment]
@olafwied Internally RVC uses your data matrix of size (n_samples, n_features) to construct kernel of size (n_samples, n_samples) and uses it instead of your X. So after kernel construction number of features equals n_samples. It is similar to kernel construction by SVC (but SVC uses only Mercer kernels, while RVC can use any type of kernel). 

If you want linear Model use ClassificationARD in skbayes.
