### ISSUE TITLE
Issues with near-singular data - ridge as solution?

### ISSUE THREAD

**Issue by sergeyf** [AmazaspShumik/Bayesian-Regression-Methods#4]
Hello,

When fitting `BayesianRegression` with this data:

```
X = np.array([[ 0.1,  -0.1,  -0.2,   0.02],
 [ 0.3,  -0.3,  -0.6,   0.06],
 [ 0.4,  -0.4,  -0.8,   0.08],
 [ 0.5,  -0.5,  -1.,    0.1 ]])

Y = np.array([ 0.2,  0.6,  0.8,  1. ])
```

The returned parameters are pretty crazy:

```
Out[16]: 
{'bias_term': 0.65000000000000002,
 'precision': array([[  8.15645225e+31,  -8.15645225e+31,  -1.63129045e+32,
           1.63129045e+31],
        [ -8.15645225e+31,   8.15645225e+31,   1.63129045e+32,
          -1.63129045e+31],
        [ -1.63129045e+32,   1.63129045e+32,   3.26258090e+32,
          -3.26258090e+31],
        [  1.63129045e+31,  -1.63129045e+31,  -3.26258090e+31,
           3.26258090e+30]]),
 'weights': array([ 0.18599761, -0.34392501, -0.68785002,  0.47188674])}
```

The issue is that X is nearly singular. Using ridge regression can help in such cases - would it make sense to add a scaled identity to the covariance/precision somewhere along the line to deal with cases like this?

**Comment by sergeyf** [comment]
My suggestion is after computing `self.d`, just do something like this:

```
self.d += lam
```

where `lam` is some small value like `1e-6` that is passed to `__init__`.

**Comment by sergeyf** [comment]
Actually, now that I'm doing more experimentation, it seems that even adding the ridge regularization doesn't get rid of the issue. What I'm seeing that `self.beta` is extremely unstable from run to run for the `X` matrix I described above. Switching to EM resolves the issue, but a non-zero lambda is still required to avoid nonsensical `self.D`.

**Comment by AmazaspShumik** [comment]
Hi Sergey,

Thanks a lot for help !!!  I made fixes and added your example with solution to ipython notebook.

So here is list of problems I found:

 Problem N1: Infinite self.beta
============================
self.beta is precision parameter for noise, and in fixed-point iteration update rule for that parameter is self.beta = gamma / RSS (Residual Sum of Squares). In case of nearly perfect fit RSS gets very small hence beta keeps increasing and in some examples overflows and has value np.PINF.

Solution:
As a I introduced parameter lambda_0, that serves as threshold. In case RSS gets smaller than lambda_0 (which means that model fits data almost perfectly) algorithm is terminated.
Note that beta will still be large but it is supposed to be that way. In case of almost perfect fit variance of noise parameter (which by definition is 1 / beta ) should be close to zero.

Problem N2: Inversion of precision matrix
================================
In order to construct predictive distribution we need to calculate covariance matrix for coefficients, which requires inverting precision matrix ( self.w_precision ).
The way I was doing it before was mathematically correct but seems to be numerically unstable for large betas. I wrote code to compare two inversion methods

def inversion_checker(X,alpha,beta):
    '''
    Checks accuracy of inversion
    '''
    n,m    = X.shape
    u,d,vh = np.linalg.svd(X,full_matrices = False)
    dsq    = d**2
    # precision matrix
    S      = beta*np.dot(X.T,X) + alpha*np.eye(m)
    
    # inverting precision : PREVIOUS VERSION
    a1     = np.dot( np.dot(vh.T, np.diag( 1. / (beta*dsq + alpha)) ), vh)
    
    # inverting precision : CURRENT VERSION
    a2     = pinvh(S)
    return [a1,a2]

Here is example, comparing two inversion methods ( I added precision_inversion_tester.py file to repository, so you can reproduce example below):

 Example 1: beta = 1000 

Previous inversion method 

[[ 0.55634511  0.11032155  0.22064311 -0.02206431]
 [ 0.11032155  0.55634511 -0.22064311  0.02206431]
 [ 0.22064311 -0.22064311  0.22538045  0.04412862]
 [-0.02206431  0.02206431  0.04412862  0.6622538 ]]

 Current inversion method 

[[ 0.55634511  0.11032155  0.22064311 -0.02206431]
 [ 0.11032155  0.55634511 -0.22064311  0.02206431]
 [ 0.22064311 -0.22064311  0.22538045  0.04412862]
 [-0.02206431  0.02206431  0.04412862  0.6622538 ]]

 Example 2: beta = 1e+30  

Previous inversion method 

[[ 0.55534508  0.11018413  0.22036826 -0.02212214]
 [ 0.11018413  0.55625278 -0.22082777  0.02206555]
 [ 0.22036826 -0.22082777  0.22501113  0.04413109]
 [-0.02212214  0.02206555  0.04413109  0.66224931]]

 Current inversion method 

[[  5.37472127e-32  -5.37472127e-32  -1.07494425e-31   1.07494425e-32]
 [ -5.37472127e-32   5.37472127e-32   1.07494425e-31  -1.07494425e-32]
 [ -1.07494425e-31   1.07494425e-31   2.14988851e-31  -2.14988851e-32]
 [  1.07494425e-32  -1.07494425e-32  -2.14988851e-32   2.14988851e-33]]

Solution:
 I changed inversion method and now I use spicy.linalg.pinvh for inversion

**Comment by sergeyf** [comment]
Thanks! I received your reply in an email but it seems to be missing here. I'll go ahead and close this issue.

**Comment by AmazaspShumik** [comment]
Hi Sergey, I changed code and added your example in ipython notebooks for both Bayesian Regression and RVM. Will do the same for Variational RVM and Variational Linear Regression.
Thanks again for your help!

**Comment by sergeyf** [comment]
Happy to help!
